# Generated by Django 4.0.4 on 2022-07-03 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('postcode', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'shipping_address',
                'ordering': ('-created',),
            },
        ),
    ]
